# Generated by Django 4.0.5 on 2023-02-27 02:35

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0015_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.product_preview_directory_path),
        ),
    ]
